@host = http://127.0.0.1:6000/v1/cats


### Get all cats
GET {{host}}/?fields=name&offset=0&limit=3 HTTP/1.1


### Create new cat
POST {{host}}/ HTTP/1.1
Content-Type: application/json

{
    "id": 0,
    "name": "El Gato"
}


### Update Cat
PUT {{host}}/ HTTP/1.1
Content-Type: application/json

{
    "id": 8,
    "name": "KAT"
}


### Delete Cat
DELETE {{host}}/ HTTP/1.1
Content-Type: application/json

[7]



### Get single cat
GET {{host}}/24?fields=id HTTP/1.1


### Update single cat
PUT {{host}}/5 HTTP/1.1
Content-Type: application/json

{
  "id": 0, 
  "name": "Garfield"
}


###
DELETE {{host}}/22 HTTP/1.1